<a href="https://colab.research.google.com/github/OscarLoOscar/python_Data_Science/blob/main/lesson2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
listA = [123,456,889,990,'abc']
print(listA)

listA.remove(123)
print(listA)

listA.remove('abc')
print(listA)

#copy
aaa = listA.copy()
print(aaa)

#pop,會return返123
listA.pop:(123)
print(listA)

[123, 456, 889, 990, 'abc']
[456, 889, 990, 'abc']
[456, 889, 990]
[456, 889, 990]
[456, 889, 990]


In [ ]:
# 直接用command＋＋ / 就出到 #號效果


In [ ]:
# return and print 分別
# colab會直接print最尾一句

def plusone(x):
  return(x+1)

plusone(10)

11

In [ ]:
list1 = [10,20,30]

def multiplyTWO(x):
  return(x*2)

print(list(map(multiplyTWO,list1))) #map base on 每個DATA run 每個FUNCTIONFUNCTION


[20, 40, 60]


In [ ]:
# NumPy Introduction
# NumPy是Python在進行科學運算時，一個非常基礎的Package，同時也是非常核心的library，它具有下列幾個重要特色：
# 提供非常高效能的多維陣列(multi-dimensional array)數學函式庫
# 可整合C/C++及Fortran的程式碼
# 方便有用的線性代數(Linear Algebra)及傅立葉轉換(Fourier Transform)能力
# 利用NumPy Array替代Python List
# 可定義任意的數據型態(Data Type)，使得能輕易及無縫的與多種資料庫整合

In [ ]:
#lesson 2 start
import numpy as np

In [ ]:
array1 = np.array([1,2,3,4])
print(array1)

print(array1[0])

print(array1[0:3]) #頭num：係邊度開始抽，尾：抽幾多個

[1 2 3 4]
1
[1 2 3]


In [ ]:
array2 = array1[array1 % 2 == 0] #餘數

#destructive , 會扭曲入面STR
array1[array1 % 2 == 0] = -1000
print(array1)

# Non-destructive
array2 = np.where(array1 % 2 == 0,-1000,array1)
print(array2)



[    1 -1000     3 -1000]
[    1 -1000     3 -1000]


In [ ]:
#2d model
array2d = np.array([
                    [1,2,3],
                    [4,5,6]
                    ])
print(array2d[1][2])

#3d model
array3d = np.array([
                     [[1,2,3],[4,5,6]],
                     [[7,8,9],[10,11,12]]
                     ])
print(array3d[1][1][2])

6
12


In [ ]:
array1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array1d)
#變2D Form

array2d = array1d.reshape(2,6) #2行，6個colum
print(array2d)

array2d = array1d.reshape(2,-1) #-1自動計
print(array2d)

array3d = array1d.reshape(2,3,2) #2個TABLE，3行，2個colum
print(array3d)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a, b))
# print(c)

a = np.array([1,2,3])
b = np.append(a,[4,5])
print(b)

a = np.array([1,2,3])
b = np.insert(a,0,[4,5,6])
print(b)

[1 2 3 4 5]
[4 5 6 1 2 3]


In [ ]:
import pandas as pd

In [ ]:
mylist = [1,2,3,4,5]

ser1 = pd.Series(mylist)

print(ser1[0])

1


In [ ]:
# mylist = [10,20,30]
# mylist2 = ['a','b','c']
# mydict = dict(zip(mylist2,mylist))  #zip,將D野合埋一齊
# print(mydict)

ser = pd.Series(mylist)
# print(ser)

df = ser.to_frame().reset_index()
print(df)

   index  0
0      0  1
1      1  2
2      2  3
3      3  4
4      4  5


In [ ]:
from google.colab import drive
from google.colab import files
drive.mount('/content/gdrive')

df.to_csv('testing.csv' , index=False) #to_csv = save
files.download('testing.csv')

df1 = pd.read.csv('testing.csv') #read = download
print(df1)

MessageError: ignored

In [ ]:
!pip install yfinance
import yfinance as yf
df2 = yf.download(
    tickers='MSFT',
    period = '5y',
    interval = '1d')
print(df2)



[*********************100%***********************]  1 of 1 completed
                  Open        High         Low       Close   Adj Close  \
Date                                                                     
2017-05-01   68.680000   69.550003   68.500000   69.410004   64.793182   
2017-05-02   69.709999   69.709999   69.129997   69.300003   64.690491   
2017-05-03   69.379997   69.379997   68.709999   69.080002   64.485130   
2017-05-04   69.029999   69.080002   68.639999   68.809998   64.233093   
2017-05-05   68.900002   69.029999   68.489998   69.000000   64.410439   
...                ...         ...         ...         ...         ...   
2022-04-22  281.679993  283.200012  273.380005  274.029999  274.029999   
2022-04-25  273.290009  281.109985  270.769989  280.720001  280.720001   
2022-04-26  277.500000  278.359985  270.000000  270.220001  270.220001   
2022-04-27  282.100006  290.970001  279.160004  283.220001  283.220001   
2022-04-28  285.190002  290.980011  281.459

In [ ]:
print(df2.iloc[0])

print('----------------------------')
print(df2.loc["2017-05-02"])

print('----------------------------')
print(df2.loc["2017-05-02"]['Volume'])

print(df2.iloc[:,0])

print('----------------------------')
print(df2.loc[:,"Open"]) #抽COLUM

df2["Open"]

Open         6.868000e+01
High         6.955000e+01
Low          6.850000e+01
Close        6.941000e+01
Adj Close    6.479318e+01
Volume       3.195440e+07
Name: 2017-05-01 00:00:00, dtype: float64
Open         6.971000e+01
High         6.971000e+01
Low          6.913000e+01
Close        6.930000e+01
Adj Close    6.469049e+01
Volume       2.390610e+07
Name: 2017-05-02 00:00:00, dtype: float64
23906100.0
Date
2017-05-01     68.680000
2017-05-02     69.709999
2017-05-03     69.379997
2017-05-04     69.029999
2017-05-05     68.900002
                 ...    
2022-04-22    281.679993
2022-04-25    273.290009
2022-04-26    277.500000
2022-04-27    282.100006
2022-04-28    285.190002
Name: Open, Length: 1259, dtype: float64
Date
2017-05-01     68.680000
2017-05-02     69.709999
2017-05-03     69.379997
2017-05-04     69.029999
2017-05-05     68.900002
                 ...    
2022-04-22    281.679993
2022-04-25    273.290009
2022-04-26    277.500000
2022-04-27    282.100006
2022-04-28    285

Date
2017-05-01     68.680000
2017-05-02     69.709999
2017-05-03     69.379997
2017-05-04     69.029999
2017-05-05     68.900002
                 ...    
2022-04-22    281.679993
2022-04-25    273.290009
2022-04-26    277.500000
2022-04-27    282.100006
2022-04-28    285.190002
Name: Open, Length: 1259, dtype: float64

In [ ]:
print(df2.describe()) #記

print(df2.describe().loc[:,'Open']['50%']) #same as print(df2.describe()['Open']['50%'])

print(df2['Open'].quantile(0.4))

              Open         High          Low        Close    Adj Close  \
count  1259.000000  1259.000000  1259.000000  1259.000000  1259.000000   
mean    169.612081   171.271056   167.832311   169.640580   166.569735   
std      79.580267    80.379891    78.698787    79.575730    80.795559   
min      67.400002    68.099998    67.139999    67.480003    63.352615   
25%     102.580002   103.595001   101.559998   102.404999    98.482918   
50%     140.949997   144.419998   139.520004   141.029999   137.482391   
75%     230.139999   233.320000   227.305000   229.940002   227.820587   
max     344.619995   349.670013   342.200012   343.109985   342.402008   

             Volume  
count  1.259000e+03  
mean   2.934865e+07  
std    1.303197e+07  
min    7.425600e+06  
25%    2.117735e+07  
50%    2.606870e+07  
75%    3.354800e+07  
max    1.112421e+08  
140.9499969482422
124.26600189208985


In [ ]:
#sorting
print(df2['Open'].sort_values(ascending = False))
print(df2[["Open","Close"]].sort_values(by="Open"))

Date
2021-11-22    344.619995
2021-12-28    343.149994
2021-11-19    342.640015
2021-12-30    341.910004
2021-12-29    341.299988
                 ...    
2017-05-16     68.230003
2017-05-15     68.139999
2017-05-22     67.889999
2017-05-19     67.500000
2017-05-18     67.400002
Name: Open, Length: 1259, dtype: float64
                  Open       Close
Date                              
2017-05-18   67.400002   67.709999
2017-05-19   67.500000   67.690002
2017-05-22   67.889999   68.449997
2017-05-15   68.139999   68.430000
2017-05-16   68.230003   69.410004
...                ...         ...
2021-12-29  341.299988  341.950012
2021-12-30  341.910004  339.320007
2021-11-19  342.640015  343.109985
2021-12-28  343.149994  341.250000
2021-11-22  344.619995  339.829987

[1259 rows x 2 columns]


In [ ]:
!pip install chart_studio
!pip install plotly
from chart_studio import plotly as py
import plotly.graph_objs as go
import plotly.express as px

fig = px.scatter(x=[0,1,2,3,4],y=[5,6,7,8,9])

fig.show()

In [ ]:
fig = px.scatter(x=df2["Open"],y=df2["Volume"])

fig.show()